### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by zembrowski** [simondubois/unsplash-downloader#1]
Hi there,

do you consider it reasonable to add your script to [Packagist](https://packagist.org/)?

Best regards,
Krzysztof

**Comment by simondubois** [comment]
Hi zembrowski,

I have used Packagist for libraries, but never for CLI.
Do you think it is relevant ? Could you give me a use case ?

If by reasonable you mean stable, I have not encounter any issue since I use it.

PS : I see that you are learning French. You are very brave !

**Comment by zembrowski** [comment]
Salut Simon,

I understand, that you created unsplash-downloader as a CLI solution, but I don't see any argument against using it as an usual library.

I use a central folder on my remote host for all of the needed libraries. Installing a new one is easy as `composer require creator/name` and updating them `composer update`.

Even if I wouldn't use your package as a library I would set a symbolic link to the build .phar for my projects and run it with a cron job.

If any change would be made to the Unsplash API or your package would get updated - it would be just `composer update` to get the newest version on my remote host.

Moreover using [VersionEye](https://www.versioneye.com) would warn me if the dependencies are outdated. Therefore the usage of [semantic versioning Tags](http://semver.org) for your package would be very appreciated.

With "reasonable" I just meant, if it makes sense to you.

If it does not I will just use a VCS repository in my central composer.json as I did now for testing.

French is just like every other language. Just a little bit more difficult than PHP ;)

Best regards,
Krzysztof

**Comment by simondubois** [comment]
You are right.
As I tried to build a CLI with loosely coupled components, it should not be too difficult to use it as a library.

I will publish it on packagist next week.
Thank you for your feedback.

**Comment by simondubois** [comment]
Hi Krzysztof,

I have published it on [packagist](https://packagist.org/packages/simondubois/unsplash-downloader).

Thank you for this suggestion,
Have a good day.
