### ISSUE TITLE
unsplash.ini

### ISSUE THREAD

**Issue by zembrowski** [simondubois/unsplash-downloader#3]
Is it possible to point to unsplash.ini at a custom location different than the current working directory when using as cli (without having to change the code of the loadApiCredentials function in [src/Command.php](https://github.com/simondubois/unsplash-downloader/blob/master/src/Command.php))?

And is it possible to define the credentials in the [cli/index.php](https://github.com/simondubois/unsplash-downloader/blob/master/cli/index.php), when using as a library?

Thank you in advance for your answer.

Best regards,
Krzysztof

**Comment by simondubois** [comment]
That's a good idea.
I will work on it next week, and come back to you with a solution.

**Comment by zembrowski** [comment]
Hi Simon,

is there a way a may assist you what regards this enhancement?

Not sure where to start.

As I understand src/Command.php at line 43 defines the ini file and it is hard coded. So the goal would be to look at the passed parameters to check whether a different (relative) location has been defined.

How about credentials to be passed directly to the function when using as library?

Best regards,
Krzysztof

**Comment by zembrowski** [comment]
Additionally, please notice, that for the methods used in src/Unsplash.php the secret is not necessary.

Source: [Unplash-PHP Readme](https://github.com/CrewLabs/Unsplash-PHP#configuration)

**Comment by simondubois** [comment]
Hi Krzysztof,

Sorry, I was busy with job applications.

Thank you so much for your comments.
Indeed, secret is not required. Application ID is required but I have set it in src/Unsplash.php

So you do not need unsplash.ini file anymore.
Do not hesitate if you have any other issue.

**Comment by zembrowski** [comment]
Hi Simon,

I don't think hard coding the applicationId is the best solution. Firstly you just put your applicationId public (better generate a new one for yourself). Secondly how one suppose to change it, when executing the script? Change the applicationId variable in src/Unsplash.php after every update?

I played with the cli/index.php to test the usage of your scripts as a library. I wasn't successful. I would just simply like to pass the available parameters (e.g. featured and history) and additionally set my own applicationId before the run method. Do you have an idea how I could achieve it based on your cli/index.php?

Thanks in advance for your response.

**Comment by simondubois** [comment]
Hi Krzysztof,

You are absolutely right. The application ID should not be hard-coded but placed in configuration.
However, I have broken this rule in this CLI for two reasons :
1. (IMO) end users should not need to bother about application ID to download photos. It is an action that anybody can do from Unsplash website. Why should it be more complicated from a CLI ?
2. only calls to public API methods are performed. I do not see why someone would want to use its own application ID. Just more work with fewer benefits.

To use it as a library (e.g. in another system, without running it from the command line), you should not call the file ``cli/index.php``. This file is responsible for starting the command line controller, nothing else.
Instead, call methods on ``src/Unsplash.php``. It is the only one file that you need to call. Examples of call to this class can be found in ``src/Task.php``.

If you need some help, show me your code and what you want to achieve, and I will do my best.

Regards,
Simon
