### ISSUE TITLE
Semantic versioning and dependency

### ISSUE THREAD

**Issue by zembrowski** [simondubois/unsplash-downloader#4]
I'm convinced, that using [Semantic Versioning](http://semver.org) is useful. Could you please consider it in future tags? Furthermore, one dependency seems to be outdated.

All info thanks to [VersionEye](https://www.versioneye.com/php/simondubois:unsplash-downloader/2.2).

Cheers,
Krzysztof

**Comment by simondubois** [comment]
Hi ,

Thanks for your feedback.
Indeed, semantic versioning is a great concept, and I thought I was following its requirements.
[It is now fixed with version 2.3.0](https://www.versioneye.com/php/simondubois:unsplash-downloader/2.3.0).

Have a good day,
Simon
