### ISSUE TITLE
Images are downloaded into the working directory and destination directory

### ISSUE THREAD

**Issue by matt-bailey** [simondubois/unsplash-downloader#5]
I've just tried this tool and it works great, except the images are downloaded into the working directory and destination directory.

For example, running `php build/unsplash-downloader --destination downloads/` from the working directory has the following result:

![screenshot 2016-12-02 11 44 40](https://cloud.githubusercontent.com/assets/969385/20832894/bed3b132-b884-11e6-8b7a-4cf0c5d7e07b.png)

**Comment by matt-bailey** [comment]
That's strange. I deleted the images, ran the command again and it's fine now :)

**Comment by simondubois** [comment]
Hey Matt,

Thank you for your feedback.
I still use this script every ten day (each time the newsletter land in my mailbox), and I have not met that bug yet.

Do not hesitate if this happen again.
